app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8080:8080"
  volumes:
    - .:/root/HelloFluent
  command: bash -c "cd /root/HelloFluent && swift package clean && swift build && ./.build/debug/HelloFluent"
